//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Nhom4QuanLyBanThucPham.Module.BusinessObjects.ORMDataModel1
{

    public partial class Chitietdonhang : XPObject
    {
        SanPham fidSP;
        [Association(@"ChitiethoadonReferencesSanPham")]
        public SanPham idSP
        {
            get { return fidSP; }
            set { SetPropertyValue<SanPham>(nameof(idSP), ref fidSP, value); }
        }
        Donhang fidDH;
        [Association(@"ChitiethoadonReferencesHoadon")]
        public Donhang idDH
        {
            get { return fidDH; }
            set { SetPropertyValue<Donhang>(nameof(idDH), ref fidDH, value); }
        }
        string fTenSP;
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        string fSoLuong;
        public string SoLuong
        {
            get { return fSoLuong; }
            set { SetPropertyValue<string>(nameof(SoLuong), ref fSoLuong, value); }
        }
        decimal fDongia;
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        string fTong;
        public string Tong
        {
            get { return fTong; }
            set { SetPropertyValue<string>(nameof(Tong), ref fTong, value); }
        }
    }

}
