//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Nhom4QuanLyBanThucPham.Module.BusinessObjects.ORMDataModel1
{

    public partial class Donhang : XPObject
    {
        string fidDH;
        public string idDH
        {
            get { return fidDH; }
            set { SetPropertyValue<string>(nameof(idDH), ref fidDH, value); }
        }
        Khachhang fidKH;
        [Association(@"HoadonReferencesKhachhang")]
        public Khachhang idKH
        {
            get { return fidKH; }
            set { SetPropertyValue<Khachhang>(nameof(idKH), ref fidKH, value); }
        }
        NhanVien fidNV;
        [Association(@"HoadonReferencesNhanVien")]
        public NhanVien idNV
        {
            get { return fidNV; }
            set { SetPropertyValue<NhanVien>(nameof(idNV), ref fidNV, value); }
        }
        string fNgaylap;
        public string Ngaylap
        {
            get { return fNgaylap; }
            set { SetPropertyValue<string>(nameof(Ngaylap), ref fNgaylap, value); }
        }
        string fdiachigiaohang;
        public string diachigiaohang
        {
            get { return fdiachigiaohang; }
            set { SetPropertyValue<string>(nameof(diachigiaohang), ref fdiachigiaohang, value); }
        }
        string ftonggia;
        public string tonggia
        {
            get { return ftonggia; }
            set { SetPropertyValue<string>(nameof(tonggia), ref ftonggia, value); }
        }
        [Association(@"NhanVienReferencesHoadon")]
        public XPCollection<NhanVien> NhanViens { get { return GetCollection<NhanVien>(nameof(NhanViens)); } }
        [Association(@"ChitiethoadonReferencesHoadon")]
        public XPCollection<Chitietdonhang> Chitiethoadons { get { return GetCollection<Chitietdonhang>(nameof(Chitiethoadons)); } }
    }

}
