//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Nhom4QuanLyBanThucPham.Module.BusinessObjects.ORMDataModel1
{

    public partial class Khachhang : XPObject
    {
        string fidKH;
        public string idKH
        {
            get { return fidKH; }
            set { SetPropertyValue<string>(nameof(idKH), ref fidKH, value); }
        }
        string fTenKH;
        public string TenKH
        {
            get { return fTenKH; }
            set { SetPropertyValue<string>(nameof(TenKH), ref fTenKH, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fSĐT;
        public string SĐT
        {
            get { return fSĐT; }
            set { SetPropertyValue<string>(nameof(SĐT), ref fSĐT, value); }
        }
        string fdiachi;
        public string diachi
        {
            get { return fdiachi; }
            set { SetPropertyValue<string>(nameof(diachi), ref fdiachi, value); }
        }
        NhanVien fNhanvien;
        [Association(@"KhachhangReferencesNhanVien")]
        public NhanVien Nhanvien
        {
            get { return fNhanvien; }
            set { SetPropertyValue<NhanVien>(nameof(Nhanvien), ref fNhanvien, value); }
        }
        [Association(@"HoadonReferencesKhachhang")]
        public XPCollection<Donhang> Hoadons { get { return GetCollection<Donhang>(nameof(Hoadons)); } }
    }

}
