//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Nhom4QuanLyBanThucPham.Module.BusinessObjects.ORMDataModel1
{

    public partial class Khohang : XPObject
    {
        SanPham fidSanPham;
        [Association(@"KhohangReferencesSanPham")]
        public SanPham idSanPham
        {
            get { return fidSanPham; }
            set { SetPropertyValue<SanPham>(nameof(idSanPham), ref fidSanPham, value); }
        }
        string fTenSP;
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        string fSoluong;
        public string Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<string>(nameof(Soluong), ref fSoluong, value); }
        }
        string fTonkhotoithieu;
        public string Tonkhotoithieu
        {
            get { return fTonkhotoithieu; }
            set { SetPropertyValue<string>(nameof(Tonkhotoithieu), ref fTonkhotoithieu, value); }
        }
    }

}
