//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Nhom4QuanLyBanThucPham.Module.BusinessObjects.ORMDataModel1
{

    public partial class NguoiQuanLy : XPObject
    {
        string fidQL;
        public string idQL
        {
            get { return fidQL; }
            set { SetPropertyValue<string>(nameof(idQL), ref fidQL, value); }
        }
        string fTenQL;
        public string TenQL
        {
            get { return fTenQL; }
            set { SetPropertyValue<string>(nameof(TenQL), ref fTenQL, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fSĐT;
        public string SĐT
        {
            get { return fSĐT; }
            set { SetPropertyValue<string>(nameof(SĐT), ref fSĐT, value); }
        }
        string fdiachi;
        public string diachi
        {
            get { return fdiachi; }
            set { SetPropertyValue<string>(nameof(diachi), ref fdiachi, value); }
        }
        [Association(@"NhanVienReferencesNguoiQuanLy")]
        public XPCollection<NhanVien> NhanViens { get { return GetCollection<NhanVien>(nameof(NhanViens)); } }
        [Association(@"NhacungcapReferencesNguoiQuanLy")]
        public XPCollection<Nhacungcap> Nhacungcaps { get { return GetCollection<Nhacungcap>(nameof(Nhacungcaps)); } }
    }

}
