//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Nhom4QuanLyBanThucPham.Module.BusinessObjects.ORMDataModel1
{

    public partial class Nhacungcap : XPObject
    {
        string fidNCC;
        public string idNCC
        {
            get { return fidNCC; }
            set { SetPropertyValue<string>(nameof(idNCC), ref fidNCC, value); }
        }
        string fTenNCC;
        public string TenNCC
        {
            get { return fTenNCC; }
            set { SetPropertyValue<string>(nameof(TenNCC), ref fTenNCC, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fSĐT;
        public string SĐT
        {
            get { return fSĐT; }
            set { SetPropertyValue<string>(nameof(SĐT), ref fSĐT, value); }
        }
        string fdiachi;
        public string diachi
        {
            get { return fdiachi; }
            set { SetPropertyValue<string>(nameof(diachi), ref fdiachi, value); }
        }
        NguoiQuanLy fidNQL;
        [Association(@"NhacungcapReferencesNguoiQuanLy")]
        public NguoiQuanLy idNQL
        {
            get { return fidNQL; }
            set { SetPropertyValue<NguoiQuanLy>(nameof(idNQL), ref fidNQL, value); }
        }
        [Association(@"SanPhamReferencesNhacungcap")]
        public XPCollection<SanPham> SanPhams { get { return GetCollection<SanPham>(nameof(SanPhams)); } }
    }

}
