//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Nhom4QuanLyBanThucPham.Module.BusinessObjects.ORMDataModel1
{

    public partial class NhanVien : XPObject
    {
        string fidNV;
        public string idNV
        {
            get { return fidNV; }
            set { SetPropertyValue<string>(nameof(idNV), ref fidNV, value); }
        }
        string fTenNV;
        public string TenNV
        {
            get { return fTenNV; }
            set { SetPropertyValue<string>(nameof(TenNV), ref fTenNV, value); }
        }
        string fEmail;
        public string Email
        {
            get { return fEmail; }
            set { SetPropertyValue<string>(nameof(Email), ref fEmail, value); }
        }
        string fSĐT;
        public string SĐT
        {
            get { return fSĐT; }
            set { SetPropertyValue<string>(nameof(SĐT), ref fSĐT, value); }
        }
        string fdiachi;
        public string diachi
        {
            get { return fdiachi; }
            set { SetPropertyValue<string>(nameof(diachi), ref fdiachi, value); }
        }
        string fCalamviec;
        public string Calamviec
        {
            get { return fCalamviec; }
            set { SetPropertyValue<string>(nameof(Calamviec), ref fCalamviec, value); }
        }
        string fLuong;
        public string Luong
        {
            get { return fLuong; }
            set { SetPropertyValue<string>(nameof(Luong), ref fLuong, value); }
        }
        NguoiQuanLy fidQL;
        [Association(@"NhanVienReferencesNguoiQuanLy")]
        public NguoiQuanLy idQL
        {
            get { return fidQL; }
            set { SetPropertyValue<NguoiQuanLy>(nameof(idQL), ref fidQL, value); }
        }
        Donhang fidDH;
        [Association(@"NhanVienReferencesHoadon")]
        public Donhang idDH
        {
            get { return fidDH; }
            set { SetPropertyValue<Donhang>(nameof(idDH), ref fidDH, value); }
        }
        [Association(@"KhachhangReferencesNhanVien")]
        public XPCollection<Khachhang> Khachhangs { get { return GetCollection<Khachhang>(nameof(Khachhangs)); } }
        [Association(@"HoadonReferencesNhanVien")]
        public XPCollection<Donhang> Hoadons { get { return GetCollection<Donhang>(nameof(Hoadons)); } }
    }

}
