//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Nhom4QuanLyBanThucPham.Module.BusinessObjects.ORMDataModel1
{

    public partial class SanPham : XPObject
    {
        string fidSP;
        public string idSP
        {
            get { return fidSP; }
            set { SetPropertyValue<string>(nameof(idSP), ref fidSP, value); }
        }
        string fTenSP;
        public string TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<string>(nameof(TenSP), ref fTenSP, value); }
        }
        string fMota;
        public string Mota
        {
            get { return fMota; }
            set { SetPropertyValue<string>(nameof(Mota), ref fMota, value); }
        }
        string fDanhMuc;
        public string DanhMuc
        {
            get { return fDanhMuc; }
            set { SetPropertyValue<string>(nameof(DanhMuc), ref fDanhMuc, value); }
        }
        decimal fDongia;
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        Nhacungcap fNhacungcap;
        [Association(@"SanPhamReferencesNhacungcap")]
        public Nhacungcap Nhacungcap
        {
            get { return fNhacungcap; }
            set { SetPropertyValue<Nhacungcap>(nameof(Nhacungcap), ref fNhacungcap, value); }
        }
        [Association(@"ChitiethoadonReferencesSanPham")]
        public XPCollection<Chitietdonhang> Chitiethoadons { get { return GetCollection<Chitietdonhang>(nameof(Chitiethoadons)); } }
        [Association(@"KhohangReferencesSanPham")]
        public XPCollection<Khohang> Khohangs { get { return GetCollection<Khohang>(nameof(Khohangs)); } }
    }

}
